package com.bidding.sellservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Product")
public class ProductInfo {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	public String id;
	@DynamoDBAttribute(attributeName = "ProductName")
	private String productName;
	@DynamoDBAttribute(attributeName = "ShortDescription")
	private String shortDescription;
	@DynamoDBAttribute(attributeName = "DetailDescription")
	private String detailDescription;
	@DynamoDBAttribute(attributeName = "Category")
	private String category;
	@DynamoDBAttribute(attributeName = "StartingPrice")
	private int startingPrice;
	@DynamoDBAttribute(attributeName = "BidEndDate")
	private String bidEndDate;
	@DynamoDBAttribute(attributeName = "SellerInfo")
	private SellerInfo sellerInfo;

}
